

# This file was *autogenerated* from the file tc.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_251 = Integer(251); _sage_const_128 = Integer(128); _sage_const_73 = Integer(73); _sage_const_71 = Integer(71); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
from sage.all import *
import configreader
import socketserver
import auxmath
import pickle
from shamir import Shamir

class Member:
	shares = []
	def __init__(self, f,g,F,G,NN):
		self.f = f
		self.g = g
		self.F = F
		self.G = G
		self.NN = NN
	
	def calculate_params(self, N, q, T = 'transpose'):
		if T == 'standard':
			self.fs = self.F
		elif T == 'transpose':
			self.fs = self.g
		self.h = auxmath.h_from_fg(self.f,self.g,N,q)
		
	def eval_k(self):
		# save unsigned values, remember it
		f_bin  = ''.join([bin(abs(x))[_sage_const_2 :] for x in  self.f.list()])
		fs_bin = ''.join([bin(abs(x))[_sage_const_2 :] for x in self.fs.list()])
		h_bin  = ''.join([bin(abs(x))[_sage_const_2 :] for x in self.h.list()])
		self.k = int(bin(len(f_bin))[_sage_const_2 :] + bin(len(fs_bin))[_sage_const_2 :] + f_bin + fs_bin + h_bin, _sage_const_2 )
		
	def update_ms(self, m, s):
		self.m = m
		self.s = s


class TC_():
	NN = _sage_const_251 
	q = _sage_const_128 
	df = _sage_const_73 
	dg = _sage_const_71 
	t = _sage_const_2 
	n = _sage_const_3 
	T = 'transpose'

	members = []
	users_count = _sage_const_0 

	def __init__(self):
		for i in range(self.n + _sage_const_1 ):
			print (i)
			self.add_member() 
		f_bin  = ''.join(['0' * (self.NN - len(self.members[_sage_const_0 ].f.list()))]  + [bin(abs(x))[_sage_const_2 :] for x in  self.members[_sage_const_0 ].f.list()])
		fs_bin = ''.join(['0' * (self.NN - len(self.members[_sage_const_0 ].fs.list()))] + [bin(abs(x))[_sage_const_2 :] for x in self.members[_sage_const_0 ].fs.list()])
		self.share_secret()

	def add_member(self):
		f,g,F,G = auxmath.gen_NTRU_fgFG(self.NN, self.q)
		m = Member(f,g,F,G, self.NN)
		m.calculate_params(self.NN, self.q, self.T)
		m.eval_k()
		self.members.append(m)

	def get_new_member_params(self):
		if self.users_count == n:
			print ('All clients already connected')
			return pickle.dumps([-_sage_const_1 , -_sage_const_1 , -_sage_const_1 ])
		self.users_count += _sage_const_1 
		f = self.members[self.users_count].f
		h = self.members[self.users_count].h
		fs = self.members[self.users_count].fs
		h0 = self.members[_sage_const_0 ].h
		shares = self.members[self.users_count].shares
		return pickle.dumps([self.users_count, f, fs, h, shares, h0, self.NN, self.q])

	def share_secret(self):
		shaTSS = Shamir(self.t, self.n)
		self.p, alpha = shaTSS.GC(_sage_const_128 )
		shares = shaTSS.DS(self.p, alpha, self.members[_sage_const_0 ].k)
		for i in range(_sage_const_1 , self.n+_sage_const_1 ):
			self.members[i].shares = shares[i-_sage_const_1 ]
		print ('sended shaTSS')

	def get_info(self):
		return pickle.dumps([self.q, self.members[_sage_const_0 ].h, self.p, self.t, self.n, self.NN])


# class TCPHandler(socketserver.BaseRequestHandler):
# 	def handle(self):
# 		global TC
# 		self.data = self.request.recv(1024).strip()
# 		if len(self.data) < 6:
# 			print ("Invalid size of request's buffer")
# 		command, data = self.data[:8], self.data[8:]
# 		print(command, data)

# 		if b'connect' in command:
# 			response = TC.get_new_member_params()
# 		elif b'info' in command:
# 			response = TC.get_info()
# 		else:
# 			print ('Invalid command')

# 		self.request.sendall(response)

# if __name__ == "__main__":
# 	HOST, PORT = "localhost", 8844
# 	with socketserver.TCPServer((HOST, PORT), TCPHandler) as server:
# 		server.serve_forever()

